# 03-1.불필요한 데이터 삭제하기

In [1]:
import gdown

gdown.download('https://bit.ly/3RhoNho', 'ns_202104.csv', quiet=False)

Downloading...
From: https://bit.ly/3RhoNho
To: /content/ns_202104.csv
100%|██████████| 57.6M/57.6M [00:00<00:00, 63.0MB/s]

'ns_202104.csv'

In [ ]:
열 삭제하기

In [2]:
import pandas as pd

ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
#전체 스캔: 파일을 쪼개서 읽지 않고, 파일 전체를 한꺼번에 메모리에 다 올립니다.
ns_df. head() # head는 처음 5개 행

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [3]:
ns_book = ns_df.loc[:, '번호':'등록일자']
#loc매서드는 슬라이싱으로 번호~등록일자 열까지 선택
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

중간에 있는 '부가기호'열을 제외하자
불리언 배열(boolean array) 사용

In [5]:
print(ns_df.columns)
# '번호', '도서명', '저자' ... 이 이름표들 자체가 다 글자죠?
# 그래서 이 이름표들을 모아놓은 인덱스(Index) 덩어리도 **"글자들로 이루어진 묶음이다"**라는 뜻에서 dtype='object'라고 표시되는 것입니다.

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')

In [ ]:
print(ns_df.columns[0])

번호

In [ ]:
ns_df.columns != 'Unnamed: 13'
# != "같지 않다"
# 결과는 넘파이 배열(Numpy array) 파이썬 리스트와 비슷한 것.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [7]:
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns] ##true인열의 모든 행을 선택
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

이제는 데이터프레임 중간에 '부가기호'를 제외해보자.

In [8]:
selected_columns = ns_df.columns != '부가기호'
ns_book = ns_df.loc[:, selected_columns] ##True인 열의 모든 행을 선택한다!
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,1,0,2021-03-19,NaN

데이터 프레임의 메서드를 사용하여 열을 삭제, 판다스에서는 데이터프레임의 행이나 열을 삭제하는 drop() 매서드를 제공, drop() 메서드로 열을 삭제하려면 첫번째 매개변수에 삭제하려는 열 이름을 전달하고 axis매개변수를 1로 지정!

In [9]:
ns_book = ns_df.drop('Unnamed: 13', axis=1)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [11]:
ns_book = ns_df.drop(['부가기호','Unnamed: 13'], axis=1)
#여러 개의 열을 삭제하려면 리스트 형식 사용합니다.
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,1,0,2021-03-19

지금까지는 ns_df데이터프레임에서 열을 삭제한 결과를 ns_book이라는 변수에 저장했습니다. drop() 매서드에 inplace매개변수를 True로 지정하면, 현재 선택한 데이터프레임을 바로 수정할 수도 있습니다. 앞서 생성한 ns_book데이터프레임의 '주제분류번호'열을 삭제해보자.

In [ ]:
ns_book.drop('주제분류번호', axis=1, inplace=True)
#복사본이 아니라, 원본(ns_book) 그 자체를 수정해 버립니다.
#책에서 이 옵션을 쓴 이유는, 앞으로 계속 '주제분류번호'가 없는 상태의 ns_book을 쓸 것이기 때문에, 번거롭게 다시 저장하지 않고 그 자리에서 바로 없애버린 거예요.
ns_book.head()

판다스는 비어있는 값을 NaN으로 표시합니다. drop()메서드와 비슷한 dropna()메서드는 기본적으로 NaN이 하나 이상 포함된 행이나 열을 삭제. axis=1로 지정하여 ns_df데이터프레임에서 NaN이 포함된 열을 삭제! 14개의 열이5개로 확 줄어듭니다. 삭제된열에는 NaN이 적어도 하나 이상 있었나 봅니다.

In [12]:
ns_book = ns_df.dropna(axis=1)
ns_book.head()

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9788937444319     1     0  2021-03-19
1   2  9791190123969     1     0  2021-03-19
2   3  9788968332982     1     0  2021-03-19
3   4  9788970759906     1     0  2021-03-19
4   5  9788934990833     1     0  2021-03-19

In [13]:
ns_book = ns_df.dropna(axis=1, how='all')
# 모든 값이 NaN인 열을 삭제하려면, how='all'
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

지금까지 열 삭제하는 방법, loc메서드로 슬라이스 연산자나 불리언 배열을 사용할 수 있다. drop()메서드, NaN이 들어있는열을 삭제하려면 dropna()메서드에 axis=1을 지정한다.

# 행 삭제하기

이번에는 행 삭제, axis매개변수를 0으로 지정하면 됨. 기본값이 0이기에 생략해도 괜찮아.

In [14]:
ns_book2 = ns_book.drop([0,1]) #처음 2개 행 삭제
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021,9791189550370,NaN,NaN,NaN,NaN,1,0,2021-03-19
6,7,아르센 벵거 자서전 My Life in Red and White,"아르센 벵거 지음, 이성모 옮김",한즈미디어(한스미디어),2021,9791160075793,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [15]:
ns_book2 = ns_book[2:]
ns_book2.head()
#[]연산자에 열이름 또는 열 이름 리스트를 전달하여 데이터프레임의 열을 선택할 수 있었다.

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021,9791189550370,NaN,NaN,NaN,NaN,1,0,2021-03-19
6,7,아르센 벵거 자서전 My Life in Red and White,"아르센 벵거 지음, 이성모 옮김",한즈미디어(한스미디어),2021,9791160075793,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [16]:
ns_book2 = ns_book[0:2]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

불리언 배열을 사용하여 행 선택.
비교연산자를황용해 원하는 행은 True로 표시하고 제외할 행은 False로 표시한 불리언 배열을 만들어 사용!

In [17]:
selected_rows = ns_df['출판사'] == '한빛미디어'
ns_book2 = ns_book[selected_rows]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
60,61,(맛있는 디자인)프리미어 프로 CC: 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원,심수진,윤성우,김덕영 지음",한빛미디어,2021,9791162244029,NaN,1,2021,005.567,1,1,2021-03-15
70,71,처음 배우는 애저 (Azure Portal로 배우는 애저 도입부터 활용까지),김도균,한빛미디어,2020,9791162243695,NaN,NaN,NaN,005.74,1,1,2021-03-15
88,89,맛있는 디자인 프리미어 프로 CC 2021 - 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원, 심수진, 윤성우, 김덕영 (지은이)",한빛미디어,2021,9791162244029,NaN,NaN,NaN,NaN,0,0,2021-03-15
156,157,"실전 보고서 작성 기술 with 파워포인트, 워드, 한글",홍장표 지음,한빛미디어,2020,9791162243763,NaN,NaN,NaN,NaN,1,0,2021-03-12
198,199,처음 배우는 리액트 네이티브,김범준 지음,한빛미디어,2021,9791162243879,NaN,NaN,NaN,NaN,1,0,2021-03-12

In [18]:
ns_book2= ns_book.loc[selected_rows]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
60,61,(맛있는 디자인)프리미어 프로 CC: 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원,심수진,윤성우,김덕영 지음",한빛미디어,2021,9791162244029,NaN,1,2021,005.567,1,1,2021-03-15
70,71,처음 배우는 애저 (Azure Portal로 배우는 애저 도입부터 활용까지),김도균,한빛미디어,2020,9791162243695,NaN,NaN,NaN,005.74,1,1,2021-03-15
88,89,맛있는 디자인 프리미어 프로 CC 2021 - 쉽게 배워 제대로 써먹는 유튜브 영상 편집,"정지원, 심수진, 윤성우, 김덕영 (지은이)",한빛미디어,2021,9791162244029,NaN,NaN,NaN,NaN,0,0,2021-03-15
156,157,"실전 보고서 작성 기술 with 파워포인트, 워드, 한글",홍장표 지음,한빛미디어,2020,9791162243763,NaN,NaN,NaN,NaN,1,0,2021-03-12
198,199,처음 배우는 리액트 네이티브,김범준 지음,한빛미디어,2021,9791162243879,NaN,NaN,NaN,NaN,1,0,2021-03-12

In [19]:
ns_book2 = ns_book[ns_book['대출건수'] > 1000]
ns_book2.head()
# 결론부터 말씀드리면, 파이썬은 전혀 헷갈려 하지 않아요. 하지만 이전에 했던 작업이 덮어씌워져서 사라지는 문제는 발생합니다.

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
94781,94782,"사피엔스 :유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문",유발 하라리 지음 ;조현욱 옮김,김영사,2016,9788934972464,NaN,NaN,NaN,909,30,1468,2016-04-22
346944,346945,해커스 토익:Listening,David Cho 지음,해커스어학연구소,2005,9788990700148,NaN,1,NaN,740.77,29,1065,2005-02-01

지금까지 불필요한 행을 삭제하거나 제외하는 방법을 알아보았습니다. 열을 삭제할 때와 마찬가지로 행을 삭제할 때도 loc메서드, drop()메서드, dropna()메서드를 모두 사용할 수 있지만,

불리언 배열을[]연산자에 전달하는 방법을 자주 사용한다는 것을 기억하세요!!!

# 중복된 행 찾기

판다스 데이터프레임의 중복된 행은 duplicated()메서드를 사용

중복된 행 중에서 처음 행을 제외한 나머지 행은 True로, 그외에 중복되지 않은 나머지 모든 행은 False로 표시한 불리언 배열을 반환한다.

In [21]:
sum(ns_book.duplicated())
# 중복된 행이 없다는 뜻!! 이처럼 duplicated()메서드는 기본적으로 데이터프레임에 있는 모든 열을 기준으로 중복된 행을 찾는다!

0

In [22]:
sum(ns_book.duplicated(subset=['도서명','저자','ISBN']))

22096

'도서명','저자','ISBN'을 기준으로 중복된 행이 있는지를 찾아보면 어떨까요?
일부 열을 기준으로 중복된 행을 찾으려면 duplicated()메서드의 **subset매개변수**에 기준열을 나열한다!!

'도서명','저자','ISBN'을 기준으로 찾으면 중복된 행이 2만개가 넘는다!!

In [23]:
dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN'], keep=False) #중복된 행을 모두 True로 표시한 불리언 배열을 반환합니다.
ns_book3 = ns_book[dup_rows]
ns_book3.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
109,110,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
110,111,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129822,9788970129808,0,2,843.6,1,0,2021-03-12
111,112,보건교사 안은영 :정세랑 장편소설,지은이: 정세랑,민음사,2021,9788937479953,NaN,0,NaN,813.7,1,0,2021-03-12
112,113,보건교사 안은영 :정세랑 장편소설,지은이: 정세랑,민음사,2021,9788937479953,NaN,0,NaN,813.7,1,1,2021-03-12
113,114,스토너,존 윌리엄스 지음 ;김승욱 옮김,RHK(알에이치코리아),2021,9788925538297,NaN,0,NaN,843.5,1,0,2021-03-12

keep='first' (기본값): "첫 번째 놈(A)은 남겨두고, 나머지(B, C)만 중복이라고 표시해." (A는 False, B와 C는 True)

keep='last': "마지막 놈(C)만 남겨두고, 앞의 놈들(A, B)을 중복이라고 표시해." (C는 False, A와 B는 True)

keep=False: "누가 처음인지 마지막인지 안 따질 거야. 중복된 게 하나라도 있으면 셋 다(A, B, C) 중복이라고 표시해!" (A, B, C 모두 True)

# 그룹별로 모으기

대출건수 열이 중요하다. 같은 도서의 대출건수를하나로 합치기. ex.'혼공 데이터 분석' 도서가 두 권이라면 하나로 합치려고 한다. groupby()메서드를 사용.

In [24]:
count_df = ns_book[['도서명','저자','ISBN','권','대출건수']] #그룹으로 묶을 기준 열
print(count_df)

                          도서명                저자           ISBN    권  대출건수
0                     인공지능과 흙            김동훈 지음  9788937444319  NaN     0
1                가짜 행복 권하는 사회            김태형 지음  9791190123969  NaN     0
2       나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음  9788968332982  NaN     0
3                     예루살렘 해변  이도 게펜 지음, 임재희 옮김  9788970759906  NaN     0
4       김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음  9788934990833  NaN     0
...                       ...               ...            ...  ...   ...
401677                韓國現代詩大系            채만묵 編著  9788977352971    3     0
401678                  뉴 웨이브        제임스 모나코 지음  9788985367448    2     0
401679           (최인훈 장편소설)화두            최인훈 지음  9788937401596    2     0
401680           독일 문학과 세계 문학            吳漢鎭 編著  9788947700368    3     0
401681             참으로 소중한 생각            김일상 지음  9788970610092    1     0

[401682 rows x 5 columns]

In [25]:
count_df = ns_book[['도서명','저자','ISBN','권','대출건수']] #그룹으로 묶을 기준 열
#필요한 재료만 도마 위에 올리기
#**"합칠 때 기준이 되는 정보"**와 **"더해야 할 대출건수"**만 쏙 뽑아서 가벼운 가방(count_df)을 먼저 만드는 거
print(count_df)

                          도서명                저자           ISBN    권  대출건수
0                     인공지능과 흙            김동훈 지음  9788937444319  NaN     0
1                가짜 행복 권하는 사회            김태형 지음  9791190123969  NaN     0
2       나도 한 문장 잘 쓰면 바랄 게 없겠네            김선영 지음  9788968332982  NaN     0
3                     예루살렘 해변  이도 게펜 지음, 임재희 옮김  9788970759906  NaN     0
4       김성곤의 중국한시기행 : 장강·황하 편            김성곤 지음  9788934990833  NaN     0
...                       ...               ...            ...  ...   ...
401677                韓國現代詩大系            채만묵 編著  9788977352971    3     0
401678                  뉴 웨이브        제임스 모나코 지음  9788985367448    2     0
401679           (최인훈 장편소설)화두            최인훈 지음  9788937401596    2     0
401680           독일 문학과 세계 문학            吳漢鎭 編著  9788947700368    3     0
401681             참으로 소중한 생각            김일상 지음  9788970610092    1     0

[401682 rows x 5 columns]

In [ ]:
group_df = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False)
#끼리끼리 모으기
#안에 적힌 네 가지 정보(제목, 저자, ISBN, 권)가 모두 똑같은 책들만 골라 하나의 그룹으로 묶어줍니다
loan_count = group_df.sum()
#팀별로 점수 합산하기
#그룹 안에 있는 책들의 대출건수를 다 더해서 하나의 숫자로 만들어줍니다.
print(loan_count)

In [ ]:
loan_count = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False).sum()
#"지름길 이용하기"
#"그룹으로 묶고(.groupby), 바로 합쳐(.sum)!"라고 한 번에 시키는 거죠.
loan_count.head()